name: Test nested level

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

permissions:
  contents: read

jobs:
  level2:
    uses: ./.github/workflows/python-publish.yml
    with:
      ref: "3b94d92602160116e1ec9ca80e05100d69395d42"
      version: "4.6.3"
      publish: false
