name: Minimal dispatch test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-publish:
    uses: ./.github/workflows/python-publish.yml
    with:
      ref: "3b94d92602160116e1ec9ca80e05100d69395d42"
      version: "4.6.3"
      publish: false
